run:
  timeout: 3m
  tests: true

linters:
  enable:
    - govet
    - staticcheck
    - revive
    - gosimple
    - ineffassign
    - errcheck
    - gocyclo
    - goconst
    - gofumpt
    - misspell

linters-settings:
  revive:
    rules:
      - name: exported
        arguments: ["checkPrivateReceivers", "sayRepetitiveInsteadOfStutters"]
      - name: indent-error-flow
      - name: error-naming
  gocyclo:
    min-complexity: 15

issues:
  exclude-use-default: false
  exclude-rules:
    - path: _test\.go
      linters: [gocyclo]
